services:
  system-monitor:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: system-monitor-dev
    network_mode: host
    volumes:
      - /:/host:rw
      - /proc:/host/proc:rw
      - /sys:/host/sys:rw
      - /dev:/host/dev:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/shadow:/host/etc/shadow:ro
      - /etc/group:/host/etc/group:ro
      - /etc/hosts:/host/etc/hosts:ro
      - /etc/resolv.conf:/host/etc/resolv.conf:ro
      - ./ssl:/app/ssl:ro
      # Mount source code for live reloading
      - ./src/server.js:/app/src/server.js:rw
      - ./public:/app/public:rw
    environment:
      - NODE_ENV=development
      - HTTP_PORT=3000
      - HTTPS_PORT=3443
    restart: unless-stopped
    privileged: true
    user: root
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - ALL
    pid: host
    # Override command to use nodemon for development
    command: npm run dev

networks:
  monitor-network:
    driver: bridge
